"""
Buda USDC/CLP trade scraper.

Mirrors the buy form at:
  https://www.buda.com/trade/usdc-clp

The page is a React SPA behind Cloudflare, so requests/BeautifulSoup can't read the
rendered numbers. We call the same backend the trade form uses:
  POST /api/v2/markets/usdc-clp/quotations   (cloudscraper clears Cloudflare)

UI mapping:
  "Pesos a gastar" (CLP to spend) ==> quotation amount, type "bid_given_spent_quote"
  "Monto" (USDC generated)        ==> response `order_amount` (gross, walks the book)

Per project spec we then subtract 0.3% from Monto ourselves (NOT Buda's own fee,
which its API reports separately as ~0.5%).
"""

import cloudscraper

BUDA_QUOTE_URL = "https://www.buda.com/api/v2/markets/usdc-clp/quotations"
BUDA_BOOK_URL = "https://www.buda.com/api/v2/markets/usdc-clp/order_book"
MANUAL_FEE_PCT = 0.3  # removed from Monto per project spec


def _scraper():
    return cloudscraper.create_scraper(
        browser={"browser": "chrome", "platform": "darwin", "mobile": False}
    )


def get_buda_asks():
    """
    Return the live ask side of the USDC-CLP order book as a list of
    (price_clp_per_usdc, size_usdc) tuples, sorted best (lowest) price first.
    Used by the optimizer to model slippage when buying USDC with CLP.
    """
    resp = _scraper().get(BUDA_BOOK_URL, timeout=40)
    resp.raise_for_status()
    asks = resp.json()["order_book"]["asks"]
    return [(float(p), float(s)) for p, s in asks]


def get_buda_quote(pesos_to_spend=10_000_000, fee_pct=MANUAL_FEE_PCT):
    """
    Simulate spending `pesos_to_spend` CLP to buy USDC on Buda, then remove
    `fee_pct`% from the resulting Monto.
    """
    scraper = cloudscraper.create_scraper(
        browser={"browser": "chrome", "platform": "darwin", "mobile": False}
    )
    payload = {
        "quotation": {
            "type": "bid_given_spent_quote",  # spend a fixed amount of quote (CLP)
            "amount": str(pesos_to_spend),
            "limit": None,                    # market order (no price limit)
        }
    }
    resp = scraper.post(
        BUDA_QUOTE_URL,
        json=payload,
        headers={"Content-Type": "application/json"},
        timeout=40,
    )
    resp.raise_for_status()
    q = resp.json()["quotation"]

    pesos_spent = float(q["amount"][0])
    monto = float(q["order_amount"][0])          # gross USDC ("Monto")
    monto_after_fee = monto * (1 - fee_pct / 100.0)

    return {
        "source": "Buda",
        "market": "USDC-CLP",
        "pesos_to_spend": pesos_spent,           # CLP
        "monto_usdc": monto,                     # USDC generated by the form (gross)
        "fee_pct": fee_pct,                      # our 0.3% deduction
        "monto_after_fee_usdc": monto_after_fee, # USDC after removing 0.3%
        # canonical direction: CLP per USDC (~ CLP per USD, USDC is USD-pegged)
        "reverse_rate": pesos_spent / monto_after_fee if monto_after_fee else None,
        "reverse_rate_gross": pesos_spent / monto if monto else None,
        "incomplete": q.get("incomplete", False),  # True if book couldn't fill it
    }


if __name__ == "__main__":
    r = get_buda_quote(10_000_000)
    print(f"Pesos a gastar : {r['pesos_to_spend']:,.0f} CLP")
    print(f"Monto (gross)  : {r['monto_usdc']:.5f} USDC")
    print(f"After -{r['fee_pct']}% : {r['monto_after_fee_usdc']:.5f} USDC")
    print(f"Effective rate : 1 USDC = {r['reverse_rate']:.4f} CLP (net of 0.3%)")
    if r["incomplete"]:
        print("  WARNING: order book could not fully fill this amount!")
